### ISSUE TITLE
Generated Barcode is not readable

### ISSUE THREAD

**Issue by nilesh211** [samt/barcode#10]
Hi,
   I followed the steps provided. I am able to generate the barcode. But the generated barcode value is not readable in barcode scanner. Can you please advise if i might have missed some steps.

**Comment by samt** [comment]
Can you attach an output image to this ticket and post a relevant code snippet?

**Comment by nilesh211** [comment]
```
var PDFDocument = require('pdfkit');
var BarCode = require('barcode');
var doc = new PDFDocument({margin: 20});
doc.pipe(res);
doc.pipe(fileSystem.createWriteStream(fPdfName));

var barCodeText = '001,221,Nilesh';
var code39 = BarCode('code39', {
    data: barCodeText,
    width: 400,
    height: 100
});

code39.getBase64(function (err, imgsrc) {
    if (err) throw err;

    doc.moveDown(0.7)
    .image(imgsrc, {
        width: 220,
        height: 25,
        x: 363,
        y: 60
    })
});
```

![image](https://cloud.githubusercontent.com/assets/11676016/6879831/9fd810d8-d533-11e4-9152-6d609a880e69.png)

**Comment by nilesh211** [comment]
I had one more query.. Suppose i need to deploy my code to hereku server then how to install graphicsmagicx in it??? i have install graphicsmagick in my system and the barcode is generated.. ..what if i deploy it in hereku server??

**Comment by samt** [comment]
If Heroku does not have Graphics Magic installed, it cannot run, I am afraid.

**Comment by nilesh211** [comment]
Thanks Sam... Can you please let me know why the barcode generated is not readable through barcode scanner?

**Comment by samt** [comment]
If you increase the pixel width of your output image, you should be able to read it with a scanner. What's going on here is that that the image is being squished which makes it hard for the scanner to distinguish between narrow bars and wide bars. 

Additionally, code39 takes a lot of space to represent the data you give it, so it's really only good for short numbers or short phrases. If your barcode gets too long with code39, you might want to try a higher density barcode or shorten your message you're sending through.

**Comment by samt** [comment]
Making this easier to surface to the user, see #14
