### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ahl5esoft** [samt/barcode#6]
``` javascript
require('barcode')('ean13', { data: '123456', width: 100, height: 50 }).getStream(function(err, s){
    console.log(s);
});
```

it will get a spawn error, why?

**Comment by my8bit** [comment]
Try to install the imagemagick graphicsmagick. If you use Linux just run:

```
sudo apt-get install imagemagick graphicsmagick
```

I hope that this going to help you.

**Comment by ahl5esoft** [comment]
already installed

**Comment by samt** [comment]
What is the error specifically?

**Comment by samt** [comment]
I am going to close this out for now, if you're still getting the error, feel free to open another issue or reopen with the error message and we can work through it.
