### ISSUE TITLE
Error: ENOENT 

### ISSUE THREAD

**Issue by tanejakaran** [samt/barcode#8]
Hi Guys,
I am using this barcode module, I did all the steps that is given in description but I am getting Below error. I have also installed imagemagick as I see on stackoverflow.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open '/home/user/application/controllers/imgs/mycode.png'

I am waiting for your response.
Thanks

**Comment by samt** [comment]
Do you have a snippet of the area of the code you think is causing this? `ENOENT` usually means the file does not exist or maybe the folder you're trying to write `mycode.png` does not exist.

**Comment by spock123** [comment]
I'm having the same issue (that's how I got here). not trying to write to a file, only to memory.
Will try to narrow down a bit more.. 

Update: OC, please try on another server.. I moved the script to another server and it worked perfectly. Must be some temporary write access error... (worked on Linux, not on OSX)
