### ISSUE TITLE
Not writing any data

### ISSUE THREAD

**Issue by computersarecool** [samt/barcode#9]
Hi,

I am trying the example exactly as it is documented but none of my files receive any data (they are written with 0 bytes).  For example:

```
var barcode = require('barcode');
var outfile = 'done.png';

var code39 = barcode('code39', {
  data: "it works",
  width: 400,
  height: 100,
});

code39.saveImage(outfile, function (err) {
  if (err) throw err;
  console.log('File has been written!');
});
```

Says "File has been written" but there is no data there.  The same is true with the other examples (piping for example).

**Comment by samt** [comment]
Can you run this command in the terminal or command prompt and post the output here?

```
gm -version
```

I got this when copy/pasting the exact code you posted:

![done](https://cloud.githubusercontent.com/assets/150040/6220134/40898e92-b5e7-11e4-9ad9-eb688c46117d.png)

**Comment by computersarecool** [comment]
```
dyld: Library not loaded: /usr/local/lib/libfreetype.6.dylib
  Referenced from: /usr/local/bin/gm
  Reason: Incompatible library version: gm requires version 18.0.0 or later, but libfreetype.6.dylib provides version 16.0.0
Trace/BPT trap: 5
```

**Comment by samt** [comment]
It looks like the GraphicMagick install went bad or is out of date. If you're on a mac, I would recommend updating graphicsmagick:

```
brew update && brew upgrade
```

And try running your js again.

**Comment by computersarecool** [comment]
Got it. You were right, I did a bunch of weird symlinking and it works now.  Thanks for the help and this project.
